### ISSUE TITLE
Strange parseTree from 'jsonc-parser' error ('jsonc-parser' is a CommonJS module, which may not support all module.exports as named exports.)

### ISSUE THREAD

**Issue by Zer0xxxx** [google/wireit#1111] opened 2024-06-24 17:43 UTC
When I start my Docker container, I get this error:

```
file:///root/.bun/install/global/node_modules/wireit/lib/util/ast.js:7
import { parseTree as parseTreeInternal } from 'jsonc-parser';
         ^^^^^^^^^
SyntaxError: Named export 'parseTree' not found. The requested module 'jsonc-parser' is a CommonJS module, which may not support all module.exports as named exports.
```

I've only noticed it today, it worked properly some days ago.

I'm using:
- Bun v1.1.15
- Dockerfile based on ubuntu:24.04
- Wireit v0.14.4

wireit is globally installed with my Dockerfile, using: `bun i -g wireit`
(Also tried `bun i -g wireit@0.14.4`, didn't change the result.)

**Comment by rschaufler** [comment] 2024-06-24 17:47
i am encountering this issue too. It seems to be related to a resent update of the jsonc-parser package, specifically this commit where an export section was added to the package.json: https://github.com/microsoft/node-jsonc-parser/commit/4f3cf98cce5634cf181786324dba09a2bc70e78a

**Comment by rschaufler** [comment] 2024-06-24 17:57
@Zer0xxxx you can workaround this issue by locking `jsonc-parser` to version `3.2.1` in your project until a fix is released.

**Comment by rschaufler** [comment] 2024-06-24 18:03
for any pnpm user, it works by putting the following section into your package.json:

```
  "pnpm": {
    "overrides": {
      "jsonc-parser": "~3.2.1"
    }
  }
```

**Comment by Zer0xxxx** [comment] 2024-06-24 18:06
> for any pnpm user, it works by putting the following section into your package.json:
> 
> ```
>   "pnpm": {
>     "overrides": {
>       "jsonc-parser": "~3.2.1"
>     }
>   }
> ```

Lmao, this is also what is intended to work with Bun, but since I'm globally installing wireit in my Docker container, it seems like I'm doomed. Gonna investigate.

**Comment by Zer0xxxx** [comment] 2024-06-24 18:09
Installed wireit as a dependency in my _package.json_ (and NOT as a dev dependency since I'm using `bun i --production`). Used the same overrides section, and now it's working again.

Looking forward to see it properly patched.

**Comment by Zer0xxxx** [comment] 2024-06-24 22:22
Heya @rschaufler 
This seems to be fixed https://github.com/microsoft/node-jsonc-parser/issues/91

Also, even if it wasn't totally from the Wireit side, maybe wireit should be more strict on its dependencies?

**Comment by rictic** [comment] 2024-06-24 22:38
Locking in deps to specific versions has pros and cons. We miss bug fixes, and a using package can lose out on opportunities to deduplicate common deps.

The strategy of installing wireit in each monorepo or package root that uses wireit and using a lockfile would have prevented this breakage, and is a good practice overall IMO.

**Comment by rschaufler** [comment] 2024-06-25 08:54
@rictic i am working in a Monorepo with a lockfile. It however doesn't prevent the breakage because the dependency will be updated if you run a update on your packages to apply patch and minor updates. However, the issue is now fixed thanks to @Zer0xxxx issue report at node-jsonc-parser.

**Comment by Zer0xxxx** [comment] 2024-06-25 09:30
> @rictic i am working in a Monorepo with a lockfile. It however doesn't prevent the breakage because the dependency will be updated if you run a update on your packages to apply patch and minor updates. So in essence, the core issue here is that the recent minor update of node-jsonrc-parser was not backwards compatible as a minor update should be. However, the issue is now fixed thanks to @Zer0xxxx issue report at node-jsonc-parser.

Yeah. Indeed, it broke when I rebuilt from zero my container.
Seeing it like a SemVer issue from jsonc-parser seems wise to me.

I understand your points of view, and I'm also happy that everything came back to normal so fast.

Maybe we can close this issue, then?

**Comment by rictic** [comment] 2024-06-25 18:00
Yep, closing as fixed. Thanks for filing this upstream!

**Closed by rictic** 2024-06-25 18:00 UTC
